- name: Deploy /etc/hosts
  copy:
    src: hosts.generated
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

# File prevents proxmox from overwriting /etc/hosts on LXC boot.
- name: Deploy /etc/.pve-ignore.hosts
  copy:
    src: .pve-ignore.hosts
    dest: /etc/.pve-ignore.hosts
    owner: root
    group: root
    mode: 0644
