- name: Setup system defaults
  import_tasks: setup_defaults.yml

- name: Setup user and tools-bin
  import_tasks: setup_user.yml

- name: Setup SSH keys
  import_tasks: ssh.yml

- name: Setup console autologin
  import_tasks: autologin.yml
