# The user already exists (created by cloud-init), this clones tools-bin and installs its deps.
- name: Run movein.sh script
  shell: |
    set -o pipefail
    curl -fsSL https://raw.githubusercontent.com/HiredNoobs/tools-bin/refs/heads/master/bin/movein.sh \
      | bash -s {{ movein_username }}
  args:
    executable: /bin/bash
    creates: "/home/{{ movein_username }}/tools-bin/.git"
  register: movein_script

- name: Check out tools-bin
  become_user: "{{ movein_username }}"
  git:
    repo: "{{ tools_bin_repo }}"
    dest: "/home/{{ movein_username }}/tools-bin"
    version: "{{ tools_bin_version }}"
  register: tools_bin_checkout

- name: Setup tools-bin
  become_user: "{{ movein_username }}"
  command: "/home/{{ movein_username }}/tools-bin/bin/setup {{ tools_bin_setup | join(' ') }}"
  when: movein_script.changed or tools_bin_checkout.changed
